# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays:
1. A 1-D array called zeros having 10 elements and all the elements are set to zero.
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [1]:
# Write your answer here
import numpy as np

#1
zeros = np.zeros(10)
print("#1: zeros: \n", zeros)
#2
vowels = np.array(['a','e','i','o','u'])
print("#2: vowels: \n", vowels)
#3
ones = np.ones(10,dtype=np.int64).reshape(2,5)
print("#3: ones: \n", ones)
#4
myarray1 = np.array([[2.7,0,-2],[3.4,10.6,0],[-19,99.9,13]])
print("#4: myarray1: \n", myarray1)
#5
myarray2 = np.arange(4, 4*15+1, 4, dtype=float).reshape(3, 5)
print("#5: myarray2: \n", myarray2)

#1: zeros: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
#2: vowels: 
 ['a' 'e' 'i' 'o' 'u']
#3: ones: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
#4: myarray1: 
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
#5: myarray2: 
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following:
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
2. Reshape the array ones to have all the 10 elements in a single row.
3. Display the 2nd and 3rd element of the array vowels.
4. Display all elements in the 2nd and 3rd row of the array myarray1.
5. Display the elements in the 1st and 2nd column of the array myarray1.
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
7. Reverse the array of vowels.

In [2]:
#Write your answer here
#1
print("#1: information ordered like this: dimension shape size data-type itemsize")
print("ones: ",ones.ndim, ones.shape, ones.size, ones.dtype, ones.itemsize )
print("vowels: ", vowels.ndim, vowels.shape, vowels.size, vowels.dtype, vowels.itemsize)
print("ones: ", ones.ndim, ones.shape, ones.size, ones.dtype, ones.itemsize)
print("myarray1: ", myarray1.ndim, myarray1.shape, myarray1.size, myarray1.dtype, myarray1.itemsize)
print("myarray2: ", myarray2.ndim, myarray2.shape, myarray2.size, myarray2.dtype, myarray2.itemsize)
#2
ones = ones.reshape(1,10)
print("#2 :\n ones after reshape:\n", ones)
#3
print("#3 2nd and 3rd elements of vowels\n", vowels[1], vowels[2])
#4
print("#4: 2nd and 3rd rows of myarray1\n", myarray1[1:3])
#5
print("#5: elements in 1st and 2nd column of myarray1: \n ", myarray1[:,0:2])
#6
print("#6: display the elements in the 1st column of the 2nd and 3rd row of myarray1 \n", myarray1[1:3,0])
#7
vowels = vowels[::-1]
print(vowels)

#1: information ordered like this: dimension shape size data-type itemsize
ones:  2 (2, 5) 10 int64 8
vowels:  1 (5,) 5 <U1 4
ones:  2 (2, 5) 10 int64 8
myarray1:  2 (3, 3) 9 float64 8
myarray2:  2 (3, 5) 15 float64 8
#2 :
 ones after reshape:
 [[1 1 1 1 1 1 1 1 1 1]]
#3 2nd and 3rd elements of vowels
 e i
#4: 2nd and 3rd rows of myarray1
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
#5: elements in 1st and 2nd column of myarray1: 
  [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
#6: display the elements in the 1st column of the 2nd and 3rd row of myarray1 
 [  3.4 -19. ]
['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3.
2. Add the arrays myarray1 and myarray2.
3. Subtract myarray1 from myarray2 and store the result in a new array.
4. Multiply myarray1 and myarray2 elementwise.
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
6. Divide myarray1 by myarray2.
7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [3]:
# Write your answer here
#1
ones = ones/3
print("#1: divided ones by 3, result = \n", ones)
#2
#sliced the last two columns of myarray2 out so it becomes compatible to be used in addition, subtraction, and elementwise multiplication
array2Slice = myarray2[:,:3]
sum = myarray1+ array2Slice
print("#2: myarray1 + myarray2 = \n", sum)
#3
subtractArray = array2Slice - myarray1
print("#3: myarray2 - myarray1 = \n",subtractArray)
#4
multArray = myarray1 * array2Slice
print("#4: elementwise mult. = \n", multArray)
#5
#matrix multiplication is doable with original arrays as dimensions are compatible
myarray3 = myarray1.dot(myarray2)
print("#5: myarray3 = \n", myarray3)
#6
#back to using the slice to divide for compatibility
divArray = myarray1/array2Slice
print("#6: division result = \n", divArray)
#7
cubeArray = (myarray1**3)/2
print("#7: result = \n", cubeArray)
#8
sqrtArray = np.round(np.sqrt(myarray2)/2,2)
print("#8: result = \n", sqrtArray)
print(myarray2.dtype)




#1: divided ones by 3, result = 
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333
  0.33333333 0.33333333 0.33333333 0.33333333]]
#2: myarray1 + myarray2 = 
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]
#3: myarray2 - myarray1 = 
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]
#4: elementwise mult. = 
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]
#5: myarray3 = 
 [[ -77.2  -74.4  -71.6  -68.8  -66. ]
 [ 268.   324.   380.   436.   492. ]
 [2893.6 3269.2 3644.8 4020.4 4396. ]]
#6: division result = 
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]
#7: result = 
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]
#8: result = 
 [[1.   1.41 1.73 2.   2.24]
 [2.45 2.65 2.83 3.   3.16]
 [3.32 3.46 3.61 3.74 3.87]]
float64


Using the arrays created above, write NumPy commands for the following:
1. Find the transpose of ones and myarray2.
2. Sort the array vowels in reverse.
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [4]:
# Write your answer here
#1
myarray2_transpose = myarray2.T
ones_transpose = ones.T
print("#1: transposes of ones and myarray2 are: \n", ones_transpose, myarray2_transpose)
#2
vowels = np.sort(vowels)[::-1]
print("2: reversing vowels back: \n", vowels)
#3
sorted_myarray1_columnwise = np.sort(myarray1, axis=0)
print("#3 sorted myarray1 : \n", sorted_myarray1_columnwise)


#1: transposes of ones and myarray2 are: 
 [[0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]
 [0.33333333]] [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
2: reversing vowels back: 
 ['u' 'o' 'i' 'e' 'a']
#3 sorted myarray1 : 
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [5]:
# Write your answer here
# 14 x 3 = 42 <- number of total elements
# 41 after the initial -1 so add 0.25 41 times to find the last element = 0.25 * 41 + -1 = 9.25
myarray4 = np.arange(-1,9.26,0.25).reshape(14,3)
print("presplit array: \n", myarray4)
print("arrays after splitting into three equal parts row-wise: \n")
myarray4_split =  np.array_split(myarray4,3)
print(myarray4_split)



presplit array: 
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]
arrays after splitting into three equal parts row-wise: 

[array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ]]), array([[2.75, 3.  , 3.25],
       [3.5 , 3.75, 4.  ],
       [4.25, 4.5 , 4.75],
       [5.  , 5.25, 5.5 ],
       [5.75, 6.  , 6.25]]), array([[6.5 , 6.75, 7.  ],
       [7.25, 7.5 , 7.75],
       [8.  , 8.25, 8.5 ],
       [8.75, 9.  , 9.25]])]


Using the myarray4 created in the above questions, write commands for the following:
1. Find the sum of all elements.
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise.
4. Find the max of all elements.
5. Find the min of all elements in each row.
6. Find the mean of all elements in each row.
7. Find the standard deviation column wise.

In [6]:
# Write your ansewr here
print("each row is an answer to parts 1 to 7")
#1
sum = np.sum(myarray4)
print(sum)
#2
sum_row_wise = np.sum(myarray4, axis=1)
print(sum_row_wise)
#3
sum_col_wise = np.sum(myarray4, axis=0)
print(sum_col_wise)
#4
max = np.max(myarray4)
print(max)
#5
min_row_wise = np.min(myarray4,axis=1)
print(min_row_wise)
#6
mean_row_wise = np.mean(myarray4, axis=1)
print(mean_row_wise)
#7
std = np.std(myarray4, axis=0)
print(std)

each row is an answer to parts 1 to 7
173.25
[-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]
[54.25 57.75 61.25]
9.25
[-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]
[-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]
[3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [17]:
# Write your answer here
import pandas as pd

data = pd.read_csv( "country-capital-lat-long-population.csv")
array = data[['Country','Capital City','Latitude','Longitude']].to_numpy()
#we have 234 rows (countries) lets extract the row that contains saudi arabia
#using the mask technique, where you get a boolean array that returns true where the value matches "Saudi Arabia"
mask = array[:,0] == "Saudi Arabia"
#extract row using the mask
saudi_row = array[mask]

#1d array of riyadh coords
riyadh_coords = saudi_row[0,2:4]
#convert to float
riyadh_coords = riyadh_coords.astype(float)

#2d array of all capital coords
capital_coords = array[:,2:]
# Convert the array to float type
capital_coords = capital_coords.astype(float)

#now to broadcast the riyadh coords and subtract them from the capital coords then to measure the eucledian distance
distances_from_riyadh = np.sqrt(np.sum((capital_coords-riyadh_coords)**2,axis=1))

#find the closest distance to 0 (not including 0 which is riyadh itself)
closest_index= -1
closest_distance = np.inf
for i,d in enumerate(distances_from_riyadh):
  if d != 0:
    if d<closest_distance:
      closest_index = i
      closest_distance = d

#now we have the row of the closest capital to riyadh, lets extract it from the original array and print its information
print(array[closest_index,:])


['Bahrain' 'Al-Manamah (Manama)' 26.2154 50.5832]


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [24]:
# Write your answer here
#find the index in the array where Washington DC is
index = np.where(data == "United States of America")[0]
#get coords
#1d array of riyadh coords
washington_coords = array[index,2:4]
#convert to float
washington_coords = washington_coords.astype(float)
#converting to 1D array so I can broadcast to capital_coords
washington_coords = washington_coords.reshape(-1)
#now to broadcast the washington coords and subtract them from the capital coords then to measure the eucledian distance
distances_from_washington = np.sqrt(np.sum((capital_coords-washington_coords)**2,axis=1))
#get the indices of the top 10 closest capitals to washington using np.argsort() then slice off the first index because it is for washington itself
top_10_indices = np.argsort(distances_from_washington)[:11]
top_10_indices = top_10_indices[1:13]
#get the rows from the array that correspond to these indices and print them
top_10_closest = array[top_10_indices]
print("#1: \n",top_10_closest[:,0])
print("#2: \n", top_10_closest[:,2:4])

#1: 
 ['Canada' 'Bahamas' 'Bermuda' 'Cuba' 'Turks and Caicos Islands'
 'Cayman Islands' 'Haiti' 'Jamaica' 'Dominican Republic'
 'Saint Pierre and Miquelon']
#2: 
 [[45.4166 -75.698]
 [25.0582 -77.3431]
 [32.2915 -64.778]
 [23.1195 -82.3785]
 [21.4612 -71.1419]
 [19.2866 -81.3744]
 [18.5392 -72.335]
 [17.997 -76.7936]
 [18.4896 -69.9018]
 [46.7738 -56.1815]]
